APP_test/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^index/$', views.index, name='index'),
	url(r'^operation/$', views.operation, name='operation'),
	url(r'^tomcatData/$', views.getTomcatData, name='tomcat'),
	url(r'^oracleData/$', views.getOracleData, name='oracle'),
]

AutoOps/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^AutoOps/', include('APP_test.urls',namespace='APP'))
]

APP_test/models.py
from __future__ import unicode_literals
from django.db import models


# Create your models here.
class VM(models.Model):
	ip = models.CharField(max_length=45, null=False, default="127.0.0.1")
	host = models.CharField(max_length=25, null=False, default='redhat66')
	username = models.CharField(max_length=25, null=False, default='root')
	passward = models.CharField(max_length=25, null=False, default='rootroot')

	def __str__(self):
		return self.ip

APP_test/views.py
from django.http import JsonResponse
from django.shortcuts import render
from .tools.ssh import Task
from django.db import connection
from .tools.base import dictfetchall


def index(request):
	return render(request, 'APP_test/index.html')


# 针对tomcat服务器的操作
def operation(request):
	vm_id = request.GET.get('id')
	vm_action = request.GET.get('action')
	with connection.cursor() as cursor:
		cursor.execute('SELECT id, tomcatport, tomcathome, ipaddress, startwait, stopwait '
		               'FROM tomcatData '
		               'WHERE id = %s' % vm_id
		               )
		tomcater = dictfetchall(cursor)[0]
		# print(tomcater)
	if vm_action == 'check_tomcat':
		command = 'ifconfig'
	elif vm_action == 'start_tomcat':
		# 需要传入三个参数 home目录/端口号/启动超时时长
		tomcat_home = tomcater['tomcathome']
		tomcat_port = tomcater['tomcatport']
		start_wait = tomcater['startwait']
		# sh_dir = '/operation/tomcat/starttomcat.sh'
		command = 'sh /operation/tomcat/starttomcat.sh %s %s %s ' % (tomcat_home, tomcat_port, start_wait)
	elif vm_action == 'stop_tomcat':
		command = ''
	task_info = {
		'ip': tomcater['ipaddress'],
		'user': 'root',
		'pwd': 'rootroot',
		'cmd': command,
	}
	mytask = Task(task_info)
	message = mytask.execute()
	return JsonResponse({'message': message})


# 展示服务器列表
def getTomcatData(request):
	# 使用SQL
	with connection.cursor() as cursor:
		cursor.execute('select id, machine, tomcathome, ipaddress, description from tomcatData')
		data = dictfetchall(cursor)
	return JsonResponse(data, safe=False, json_dumps_params={'ensure_ascii': False})

def getOracleData(request):
	return JsonResponse([{'message':'ORACLE'}], safe=False)

APP_test/templates/APP_test/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <title>自动化运维</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- 引入 Bootstrap -->
    <link href="{% static 'APP_test/bootstrap3.3.7/css/bootstrap.min.css' %}" rel="stylesheet">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<header id="header">
    <div class="page-header" style="text-align:center">
        <h1>AUTO OPERATION
            <small>自动化运维平台</small>
        </h1>
    </div>
</header>
<aside id="left-panel" style="position: absolute;top: 100px;left: 0;z-index: 904;">
    <nav>
        <ul class="nav nav-pills nav-stacked">
            <li id="home" role="presentation" class="active"><a href="javascript:void(0)">主页</a></li>
            <li id="toms" role="presentation"><a href="javascript:void(0)">Tomcat 机器清单</a></li>
            <li id="oras" role="presentation"><a href="javascript:void(0)">Oracle 机器清单</a></li>
            <li id="mysqls" role="presentation"><a href="javascript:void(0)">MySql 机器清单</a></li>
        </ul>
    </nav>
</aside>
<div id="main1"
     style="margin:-20px 0 0 220px;padding:0 0 52px 0;min-height:500px;position: relative;display: none">
    <div style="height: 100%;border: 1px;">
        <div class="row">
            <ol class="breadcrumb">
                <li><a href="#">Home</a></li>
                <li class="active">Tomcat</li>
            </ol>
            <div class="col-lg-6" style="float: right">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
        <button class="btn btn-default" type="button">查找</button>
      </span>
                </div><!-- /input-group -->
            </div><!-- /.col-lg-6 -->
        </div><!-- /.row -->
        <table class="table table-hover table-condensed">
            <caption><strong>Tomcat应用服务器清单</strong></caption>
            <thead>
            <tr>
                <th>ID</th>
                <th>IP</th>
                <th>主机名</th>
                <th>概要</th>
                <th>检查</th>
                <th>开启</th>
                <th>停止</th>
            </tr>
            </thead>
            <tbody class="text">

            </tbody>
        </table>
    </div>
    <div id="tomcat_mes" class="alert alert-info alert-dismissible" role="alert">
        {#        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span#}
        {#                aria-hidden="true">&times;</span></button>#}
    </div>
</div>
<div id="main2"
     style="margin-left: 220px;padding:0 0 52px 0;min-height:500px;position: relative;display: none">
    <div style="height: 100%;border: 1px;">
        <div class="row">
            <div class="col-lg-6" style="float: right">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
        <button class="btn btn-default" type="button">查找</button>
      </span>
                </div><!-- /input-group -->
            </div><!-- /.col-lg-6 -->
        </div><!-- /.row -->
        <table class="table table-condensed">
            <caption><strong>Oracle数据库服务器清单</strong></caption>
            <thead>
            <tr>
                <th>ID</th>
                <th>IP</th>
                <th>主机名</th>
                <th>SID</th>
            </tr>
            </thead>
            <tbody class="text">

            </tbody>
        </table>
    </div>
    <div id="tomcat_mes" class="alert alert-info alert-dismissible" role="alert">
        {#        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span#}
        {#                aria-hidden="true">&times;</span></button>#}
    </div>
</div>
<div class="page-footer"></div>
<!-- 导入Jquery文件-->
<script src="{% static 'APP_test/js/jquery-3.2.1.min.js' %}"></script>
<script></script>
<!--导入bootstrap中的js 插件-->
<script src="{% static 'APP_test/bootstrap3.3.7/js/bootstrap.min.js' %}"></script>
</body>
</html>
<script>
    $("#toms").click(function () {
        $('#main2').css('display', 'none');
        $('#main1').css('display', 'block');
        $.ajax({
            type: "GET",
            url: "{% url 'APP:tomcat' %}",
            datatype: 'json',
            success: function (datas) {
                var text = $('.text');
                text.empty();
                var html = '';
                for (var i = 0; i < datas.length; i++) {
                    var id = datas[i]['id'];
                    var ip = datas[i]['ipaddress'];
                    var host = datas[i]['machine'];
                    var dec = datas[i]['description'];
                    html += '<tr>';
                    html += '<td>' + id + '</td>';
                    html += '<td>' + ip + '</td>';
                    html += '<td>' + host + '</td>';
                    html += '<td>' + dec + '</td>';
                    html += '<td>' + '<button id=' + id + ' onclick="opt_tomcat(this)" name="check_tomcat" class="btn btn-default">';
                    html += '<span class="glyphicon glyphicon-check" aria-hidden="true"></span></button></td>';
                    html += '<td>' + '<button id=' + id + ' onclick="opt_tomcat(this)" name="start_tomcat" class="btn btn-default">';
                    html += '<span class="glyphicon glyphicon-play" aria-hidden="true"></span></button></td>';
                    html += '<td>' + '<button id=' + id + ' onclick="opt_tomcat(this)" name="stop_tomcat" class="btn btn-default">';
                    html += '<span class="glyphicon glyphicon-stop" aria-hidden="true"></span></button></td>';
                    html += '</tr>';
                }
                text.append(html);
            },
            error: function (datas) {
                text.append(datas);
            }
        })
    });

    $("#oras").click(function () {
        $('#main1').css('display', 'none');
        $('#main2').css('display', 'block');
        $.ajax({
            type: "GET",
            url: "{% url 'APP:oracle' %}",
            datatype: 'json',
            success: function (datas) {
                var text = $('.text');
                text.empty();
                var html = '';
                for (var i = 0; i < datas.length; i++) {
                    var id = datas[i]['message'];
                    var ip = datas[i]['message'];
                    var host = datas[i]['message'];
                    var dec = datas[i]['message'];
                    html += '<tr>';
                    html += '<td>' + id + '</td>';
                    html += '<td>' + ip + '</td>';
                    html += '<td>' + host + '</td>';
                    html += '<td>' + dec + '</td>';
                    html += '<td>' + '<button id=' + id + ' onclick="opt_tomcat(this)" name="check_tomcat" class="btn btn-default">';
                    html += '<span class="glyphicon glyphicon-align-left" aria-hidden="true">' + '</span>';
                    html += '</button>' + '</td>';
                    html += '<td>' + '<button id=' + id + ' onclick="opt_tomcat(this)" name="start_tomcat">start</button>' + '</td>';
                    html += '<td>' + '<button id=' + id + ' onclick="opt_tomcat(this)" name="stop_tomcat">stop</button>' + '</td>';
                    html += '</tr>';
                }
                text.append(html);
            },
            error: function (datas) {
                text.append(datas);
            }
        })
    });
    function opt_tomcat(obj) {
        var id = obj.id;
        var action = obj.name;
        $.getJSON("{% url 'APP:operation' %}", {'id': id, 'action': action}, function (data) {
            $("#tomcat_mes").empty()
            $('#tomcat_mes').append(data['message'])
        })
    }

</script>